version: "3.8"

services:
  sql-judge:
    build: ./
    command: ./wait-for-postgres.sh db ./main
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - DB_PASSWORD=tempPassword11

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=tempPassword11
    ports:
      - 5436:5432