#Здесь прописывается открытый порт сервера, на который будут приходить запросы
port: "port"
#Здесь прописываются ip-адреса у которых есть доступ к веб-сервису
white-ip-4: "127.0.0.1"
white-ip-6: "::1"
#Название контейнера который будет использоваться для подключения к БД
container_name: "postgresql"
#Здесь прописываются параметры для подключения БД
db:
  host: "localhost"
  port: "5432"
  username: "postgres"
  password: ""
  name: "sqljudge"
  sslmode: "disable"
  #Здесь прописывается название роли и пароль(если есть) в БД для выполнения скриптов студентов
  student_role: "student"
  student_password: ""
#После изменений файл сохранить с названием config и расширением yml

